#logging
logging:
  level:  DEBUG  # or DEBUG, WARNING, ERROR, CRITICAL
  log_dir: "logs"  # Log directory
  log_file: "data.log"  # Log file name
  save_file: true
#numeric representation
max_base: 16
custom_digits : "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"

variable_atoms:
  - left_operand: "a"
  - right_operand: "b"

other_symbols_atoms:
  left_parenthesis: "(" 
  right_parenthesis: ")"
  equals_sign: "="
  nan_symbol: "NaN"  
  inf_symbol: "Inf"  
  neg_inf_symbol: "-Inf"  

operator_symbol_min_len: 1
operator_symbol_max_len: 3

basic_operator_symbols: ["+", "-", "*", "/", "%"]
comparison_ops: ["==", ">", "<", ">=", "<=", "!="]
logical_connectors: ["and", "or"]
condition_numeric_range: 
  max_value: 1000
  min_value: 0 
condition_probabilities:
  1: 0.7
  2: 0.2
  3: 0.1

max_if_branches: 2

expr_variables:
  - a
  - b
expr_numeric_range: 
  max_value: 1000
  min_value: 0 
expr_max_depth: 3
expr_type_weights: 
  binary: 0.7
  unary_prefix: 0.2
  unary_postfix: 0.1
  atoms: 0.1
expr_atom_type_weights: 
  variable: 0.8
  number: 0.2
random_base:
  flag: false
  base: 10
result_base: 
  random_flag: false
  base: 10
longer_result_compute:
  flag: true
  base: 10



