logging:
  level: INFO  # or DEBUG, WARNING, ERROR, CRITICAL
  log_dir: "logs"  # Log directory
  log_file: "data.log"  # Log file name
  save_file: true

max_base: 16
custom_digits : "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"

other_symbols_atoms:
  left_parenthesis: "(" 
  right_parenthesis: ")"
  equals_sign: "="
  nan_symbol: "NaN"  
  inf_symbol: "Inf"  
  neg_inf_symbol: "-Inf"  

expr_variables:
  - a
  - b
expr_numeric_range: 
  max_value: 1000
  min_value: 0 
expr_max_depth: 3
expr_type_weights: 
  binary: 0.7
  unary_prefix: 0.2
  unary_postfix: 0.1
  atoms: 0
expr_atom_type_weights: 
  variable: 0.3
  number: 0.7
random_base:
  flag: false
  base: 10
result_base: 
  random_flag: false
  base: 10
longer_result_compute:
  flag: true
  base: 10
