#logging
logging:
  level: INFO  # or DEBUG, WARNING, ERROR, CRITICAL
  log_dir: "logs"  # Log directory
  log_file: "data.log"  # Log file name

#numeric representation
max_base: 16
custom_digits : "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"

other_symbols_atoms:
  left_parenthesis: "(" 
  right_parenthesis: ")"
  equals_sign: "="
  nan_symbol: "NaN"  # 表示无解
  inf_symbol: "Inf"  # 表示无穷大
  neg_inf_symbol: "-Inf"  # 表示负无穷大

# 表达式生成
expr_variables: "a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z"
expr_numeric_range: 
  max_value: 1000
  min_value: 0 #不用负数，是因为其实一元符号里面有负数
expr_max_depth: 6
expr_type_weights: 
  binary: 0.7
  unary_prefix: 0.2
  unary_postfix: 0.1
  atoms: 0
expr_atom_type_weights: 
  variable: 0.3
  number: 0.7
random_base:
  flag: false
  base: 10
result_base: 
  random_flag: false
  base: 10
longer_result_compute:
  flag: true
  base: 10
